### PR TITLE
Make compat with stable9.1

### PR DESCRIPTION
**Pull request by tomneedham**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
no travis?
no tests?
no coverage?

@butonic one of your apps I assume 😉

**Comment by PVince81** [comment]
obsolete ? 9.1 will die very soon

**Comment by cdamken** [comment]
Well, now we have to think for 10.0.9/10

Are there any changes to 10?

@tomneedham @butonic

**Comment by DeepDiver1975** [comment]
obsolete -> close

**Pull request closed without merging**
